# Base configs
baseurl: "http://shutter.praka.sh/"
index_image_fulls_loc: "/images/index/fulls"
index_image_thumbs_loc: "/images/index/thumbs"
index_italy_fulls_loc: "/images/italy/fulls"
index_italy_thumbs_loc: "/images/italy/thumbs"
google_analytics: "-2"

# UI configs
title: "Photography by Prakash Rajendran"
subtitle: "Nothing is just what it seems!"
author: "Prakash Rajendran"
bio: "I am now learning photography."
publicise: ""
web_design: ""
social_urls:
  facebook: "https://www.facebook.com/dearprakash"
  twitter: "https://www.twitter.com/dearprakash"
  instagram: "https://www.instagram.com/dearprakash"
  github: "https://www.github.com/dearprakash"
  