# Base configs
baseurl: "http://shutter.praka.sh"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA--2"

# UI configs
title: "Photography by Prakash Rajendran"
subtitle: "Nothing is just what it seems!"
author: "Prakash Rajendran"
header:
 title: "Photography"
 subtitle: "by Prakash Rajendran"
footer:
 name: "Hey there"
 bio: " ."
 github: " ;)"
web_design: " "
social_urls:
  facebook: "https://www.facebook.com/dearprakash"
  twitter: "https://www.twitter.com/dearprakash"
  instagram: "https://www.instagram.com/dearprakash"
  github: "https://www.github.com/dearprakash"
