# Base configs
baseurl: "http://blog.praka.sh/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "-2"

# UI configs
title: "Photography by Prakash Rajendran"
subtitle: "Nothing is what it seems!"
author: "Prakash Rajendran"
bio: "I am now learning photography."
publicise: "Want a website like this for yourself for free? ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/dearprakash"
  twitter: "https://www.twitter.com/dearprakash"
  instagram: "https://www.instagram.com/dearprakash"
  github: "https://www.github.com/dearprakash"
  